config/routes.rb
Rails.application.routes.draw do
  
  
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root to: "main#index"

get "send", to: "sendmessages#new"
post "send", to: "sendmessages#create"

get "recei", to: "receive#new"
post "recei", to: "receive#show"
get "index_recei", to: "receive#index"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:body, :user_id, :published_at)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
     if session[:text_id]
        @send = Text.find(session[:text_id])
     end
     end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/receive_controller.rb
class ReceiveController < ApplicationController
before_action :set_name, only: %i[show]
before_action :get_num, only: %i[index]
def new
 
end

def show
    @recei = Text.all
    
end

def index
  @pieSize = {
    :height => 500,
    :width => 500
  }

  @pieData = [
        {
          value: 300,
          color:"#F7464A",
          highlight: "#FF5A5E",
          label: "Red"
        },
        {
          value: 50,
          color: "#46BFBD",
          highlight: "#5AD3D1",
          label: "Green"
        },
        {
          value: 100,
          color: "#FDB45C",
          highlight: "#FFC870",
          label: "Yellow"
        },
        {
          value: 40,
          color: "#949FB1",
          highlight: "#A8B3C5",
          label: "Grey"
        },
        {
          value: 120,
          color: "#4D5360",
          highlight: "#616774",
          label: "Dark Grey"
        }

      ].to_json
  
end

private
def set_name
  @recei = Text.find_by(uname: params[:uname])
end

def get_num
   @arti = Article.last(5)
   @all_num = Article.all
end

end

app/controllers/sendmessages_controller.rb
class SendmessagesController < ApplicationController

 def new
    @send = Text.new
 end

 def create
    @send = Text.new(text_params)
    if @send.save
       session[:text_id] = @send.id
        redirect_to root_path, notice: "Successfully send messages"
    else
      render new
    end
 end

 private
  def text_params
    params.require(:text).permit(:uname, :phonenum, :content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user_id %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @article.published_at %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messagingtest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial:"shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      
      
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome to messaging system</h1>
<% if @send %>
 This is what you say<%= @send.content %>
 <% end %>
</div>

app/views/receive/index.html.erb
<!DOCTYPE html>
<h1>This is your messages</h1>

<tbody class="mb-3">
    
    <% @arti.each do |article| %> 
    <div class="form-row me-4 card card-body">
     <div class=" form-group " >
        <label for="staticEmail" class="col-sm-2 col-form-label">body</label>
        <%= article.body %>
        </div>
        <div class=" form-group " >
            <label for="staticEmail" class="col-sm-2 col-form-label">created by</label>
            <%= article.user_id %>
            </div>
            <div class=" form-group " >
                <label for="staticEmail" class="col-sm-2 col-form-label">time</label>
                <%= article.published_at %>
                </div>
    </div>
    <% end %>
    
 
    </tbody>

    <br>

<div class="row justify-content-center">
    <div class="col-md-6 col-lg-3">
        <div class="card report-card">
            <div class="card-body">
                <div class="row d-flex justify-content-center">
                    <div class="col">
                        <p class="text-dark mb-0 font-weight-semibold">发送总量</p>
                        <h3 class="m-0">
                            <%= @all_num.size %>
                        </h3>
                        <p class="mb-0 text-truncate text-muted"><span class="text-success"><i class="mdi mdi-trending-up"></i>8.5%</span> New Sessions Today</p>
                    </div>
                    <div class="col-auto align-self-center">
                        <div class="report-main-icon bg-light-alt">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users align-self-center text-muted icon-sm"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>  
                        </div>
                    </div>
                </div>
            </div><!--end card-body--> 
        </div><!--end card--> 
    </div> <!--end col--> 
    <div class="col-md-6 col-lg-3">
        <div class="card report-card">
            <div class="card-body">
                <div class="row d-flex justify-content-center">                                                
                    <div class="col">
                        <p class="text-dark mb-0 font-weight-semibold">当日发送量</p>
                        <h3 class="m-0">
                            <%= @all_num.size %>
                        </h3>
                        <p class="mb-0 text-truncate text-muted"><span class="text-success"><i class="mdi mdi-trending-up"></i>1.5%</span> Weekly Avg.Sessions</p>
                    </div>
                    <div class="col-auto align-self-center">
                        <div class="report-main-icon bg-light-alt">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock align-self-center text-muted icon-sm"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>  
                        </div>
                    </div> 
                </div>
            </div><!--end card-body--> 
        </div><!--end card--> 
    </div> <!--end col--> 
    
                                 
</div>
<div>
<%= pie :pie_chart, @pieSize, @pieData%>
</div>

app/views/receive/new.html.erb
<h1>Receive messages</h1>

<%= form_with url: recei_path do |form| %>
 <div class="mb-3">
    <%= form.label :Name %>
   <%= form.text_field :uname, class: "form-control", placeholder: "Username" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Search", class: "btn btn-primary" %>
  </div> 

<% end %>

app/views/receive/show.html.erb
<h1>This is your messages</h1>
<div class="mb-3">
 
    <% @recei.where(uname: params[:uname]).each do |text| %> 
    <div class="me-4 card card-body" >
          <%= text.content %>
   </div>
    <% end %>

    
 
</div>
    
    

app/views/sendmessages/new.html.erb
<h1>Send messages</h1>

<%= form_with model: @send, url:send_path do |form| %>
 <% if @send.errors.any? %>
    <div class="alert alert-danger">
     <% @send.errors.full_messages.each do |message| %>
     <div><%= message %></div> 
     <% end %>
   </div>
      
    <% end %>
     <div class="mb-3" >
    <%= form.label :Name %>
     <%= form.text_field :uname,class: "form-control" %>
     </div>
 <div class="mb-3">
    <%= form.label :PhoneNum %>
  <%= form.text_field :phonenum, class: "form-control" %>
  </div>
 <div class="mb-3">
    <%= form.label :content %>
  <%= form.text_area :content, class: "form-control" %>
   </div>
   <div class="mb-3">
       <%= form.submit "Send", class: "btn btn-primary" %>
   </div>

 <% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4">
<%= flash[:notice] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-info mt-4">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <%= link_to "Send", send_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Receive", recei_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "text", new_article_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "messaging", index_recei_path, class:"nav-link" %>
          </li>

          
        </ul>
      </div>
    </div>
  </nav>